### ISSUE TITLE
mac m2芯片 打开安装包，无响应（安全里已信任）

### ISSUE THREAD

**Issue by dreambe** [Xigong93/XiaoZhuan#12]
mac m2芯片 打开安装包，无响应（安全里已信任）

**Comment by Xigong93** [comment]
你好，可以发一下日志看一下，日志位于home目录下的`.XiaoZhuan\log`中。

我使用m1 版本的mac测试过，我的系统是最新mac Sonoma 14.0

这个是Java的，安装包内置JDK，一般是与平台无关的，可能是启动路径或者什么原因引起的。

**Comment by dreambe** [comment]
2024-11-18 15:40:24.444 [main] Info/main: App启动
  2 2024-11-18 15:40:24.448 [main] Info/BuildConfig: 构建配置:{"versionCode":10101,"versionName":"1.1.1","packageId":"com.xigong.xiaozhuan","appName":"小篆传包","release":true}
  3 2024-11-18 15:40:25.950 [AWT-EventQueue-0] Info/启动页: 启动
  4 2024-11-18 15:40:26.018 [AWT-EventQueue-0] Info/启动页: 启动
  5 2024-11-18 15:40:26.375 [AWT-EventQueue-0] Error/检测版本更新: 失败 retrofit2.HttpException: HTTP 403
  6         at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
  7         at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:164)
  8         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
  9         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 10         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 11         at java.base/java.lang.Thread.run(Unknown Source)
 12
 13 2024-11-18 15:40:26.887 [AWT-EventQueue-0] Info/启动页: 销毁
 14 2024-11-18 15:41:59.875 [main] Info/main: App启动
 15 2024-11-18 15:41:59.879 [main] Info/BuildConfig: 构建配置:{"versionCode":10101,"versionName":"1.1.1","packageId":"com.xigong.xiaozhuan","appName":"小篆传包","release":true}
 16 2024-11-18 15:42:01.233 [AWT-EventQueue-0] Info/启动页: 启动
 17 2024-11-18 15:42:01.278 [AWT-EventQueue-0] Info/启动页: 启动
 18 2024-11-18 15:42:01.955 [AWT-EventQueue-0] Error/检测版本更新: 失败 retrofit2.HttpException: HTTP 403
 19         at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
 20         at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:164)
 21         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
 22         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 23         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 24         at java.base/java.lang.Thread.run(Unknown Source)

**Comment by dreambe** [comment]
72 2024-11-18 16:10:33.892 [main] Info/main: App启动
 73 2024-11-18 16:10:33.898 [main] Info/BuildConfig: 构建配置:{"versionCode":10101,"versionName":"1.1.1","packageId":"com.xigong.xiaozhuan","appName":"小篆传包","release":true}
 74 2024-11-18 16:10:35.544 [AWT-EventQueue-0] Info/启动页: 启动
 75 2024-11-18 16:10:35.599 [AWT-EventQueue-0] Info/启动页: 启动
 76 2024-11-18 16:10:36.335 [AWT-EventQueue-0] Info/启动页: 销毁
 77 2024-11-18 16:10:36.368 [AWT-EventQueue-0] Info/检测版本更新: 无新版本

**Comment by dreambe** [comment]
https://github.com/dxmwl/new_bee_upload_app，这个项目是抄袭吧···

**Comment by Xigong93** [comment]
不是抄袭，是fork我的仓库代码，然后增加了对蒲公英平台的支持。

**Comment by dreambe** [comment]
> 感谢反馈，我升级电脑系统试一下。 从日志上看，Compose 正常启动了，但是关联的AWT Window 却没有显示出来。

你好，请问这个有计划修复不~

**Comment by Xigong93** [comment]
不好意思，这个问题，我这边的机器复现不了。我只有一台M1的老Mac,你可以自己编译一下试试。

编译文档：https://github.com/Xigong93/XiaoZhuan/blob/main/doc/Develop.md

**Comment by dreambe** [comment]
> 不好意思，这个问题，我这边的机器复现不了。我只有一台M1的老Mac,你可以自己编译一下试试。
> 
> 编译文档：https://github.com/Xigong93/XiaoZhuan/blob/main/doc/Develop.md

一直打包失败。可以在文档中更新一下打包的依赖吗，比如需要哪些环境，跟具体支持的版本

或者说，下载源码后，没有安装compose，仅仅是下载源码后，执行编译chmod +x ./gradlew && ./gradlew packageMac，是否OK，没做过打包这块的事情，希望帮解读下，谢谢

**Comment by Xigong93** [comment]
## 1. 如何是想通过idea 运行起来，是需要安装compose 插件的

这种方式不需要电脑安装jdk ,但是可能在下载依赖的过程中会失败，需要在idea 系统设置中配置代理

## 2. 如果想直接通过命令行编译项目，流程如下：

  1). 安装jdk 17 及以上，我的电脑安装的是 Oracle jdk 17.0.11,并配置JAVA_HOME 
  2）. 执行 `chmod +x ./gradlew && ./gradlew packageMac`
  3). 如果遇到网络问题，可能会下载依赖失败， 可以让gradle通过代理的方式运行，执行命令 

 `./gradlew -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort={本机代理端口号} -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort={本机代理端口号}  packageMac`
 
 
 -----
Hello，我觉得可能是jdk 版本的问题导致的，可以安装jdk 17 再试一下，也有可能是你的gradle 目录有什么特殊的配置。

**Comment by dreambe** [comment]
> ## 1. 如何是想通过idea 运行起来，是需要安装compose 插件的
> 这种方式不需要电脑安装jdk ,但是可能在下载依赖的过程中会失败，需要在idea 系统设置中配置代理
> 
> ## 2. 如果想直接通过命令行编译项目，流程如下：
> 1). 安装jdk 17 及以上，我的电脑安装的是 Oracle jdk 17.0.11,并配置JAVA_HOME 2）. 执行 `chmod +x ./gradlew && ./gradlew packageMac` 3). 如果遇到网络问题，可能会下载依赖失败， 可以让gradle通过代理的方式运行，执行命令
> 
> `./gradlew -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort={本机代理端口号} -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort={本机代理端口号} packageMac`
> 
> Hello，我觉得可能是jdk 版本的问题导致的，可以安装jdk 17 再试一下，也有可能是你的gradle home目录有什么特殊的配置。

已解决。感谢。确实是jdk版本的问题。mac M2芯片 jdk17 编译打包成功。现在遇到别的问题，包无法打开，我再查一下原因

**Comment by dreambe** [comment]
实在搞不定了，哈哈哈。包打不开
2024-12-04 14:43:03.952 [main] Info/main: App启动
2024-12-04 14:43:03.956 [main] Info/BuildConfig: 构建配置:{"versionCode":10101,"versionName":"1.1.1","packageId":"com.xigong.xiaozhuan","appName":"小篆传包","release":true}
2024-12-04 14:43:05.122 [AWT-EventQueue-0] Info/启动页: 启动
2024-12-04 14:43:05.164 [AWT-EventQueue-0] Info/启动页: 启动
2024-12-04 14:43:06.017 [AWT-EventQueue-0] Info/启动页: 销毁
2024-12-04 14:43:06.088 [AWT-EventQueue-0] Info/检测版本更新: 无新版本

**Comment by Xigong93** [comment]
![image](https://github.com/user-attachments/assets/b6d62f99-f9c4-4f16-9500-7ca2d5f88c4a)

可以把这三个参数注释掉，再试试，有可能跟这这块儿的参数配置有关 。

**Comment by dreambe** [comment]
去掉后，可以打开。但是白屏。日志无报错。截图如下
![image](https://github.com/user-attachments/assets/f2bfc83b-94f1-4c3d-bfd9-3e00965b714e)

补充一个信息，打包的过程中，有如下提示
chmod +x ./gradlew && ./gradlew packageMac

> Configure project :
当前版本:v1.1.1 (10101)
Kotlin DSL property assignment is an incubating feature.

> Task :processResources
Write release BuildConfig.json to  /Users/ss/code/github/XiaoZhuan/build/resources/main/BuildConfig.json

> Task :compileKotlin
w: file:///Users/ss/code/github/XiaoZhuan/src/main/kotlin/com/xigong/xiaozhuan/channel/MockChannelTask.kt:29:9 Unreachable code
w: file:///Users/ss/code/github/XiaoZhuan/src/main/kotlin/com/xigong/xiaozhuan/channel/MockChannelTask.kt:35:9 Unreachable code
w: file:///Users/ss/code/github/XiaoZhuan/src/main/kotlin/com/xigong/xiaozhuan/channel/vivo/VIVOApiSigner.kt:42:13 Variable 'sb' is never used
w: file:///Users/ss/code/github/XiaoZhuan/src/main/kotlin/com/xigong/xiaozhuan/channel/vivo/VIVOMarketApi.kt:105:13 Variable 'message' is never used
w: file:///Users/ss/code/github/XiaoZhuan/src/main/kotlin/com/xigong/xiaozhuan/page/home/ApkPage.kt:51:33 Elvis operator (?:) always returns the left operand of non-nullable type String
w: file:///Users/ss/code/github/XiaoZhuan/src/main/kotlin/com/xigong/xiaozhuan/page/home/ChannelGroup.kt:79:63 Destructured parameter 'index' is never used
w: file:///Users/ss/code/github/XiaoZhuan/src/main/kotlin/com/xigong/xiaozhuan/page/upload/UploadPage.kt:55:13 Variable 'uploading' is never used

> Task :createDistributable
The distribution is written to /Users/ss/code/github/XiaoZhuan/build/packages/main/app

> Task :packageDmg
The distribution is written to /Users/ss/code/github/XiaoZhuan/build/packages/main/dmg/小篆传包-1.1.1.dmg

> Task :packageMac
The distribution is written to /Users/ss/code/github/XiaoZhuan/build/packages/XiaoZhuan-v1.1.1-Mac.dmg
BUILD SUCCESSFUL in 3m 30s
17 actionable tasks: 12 executed, 5 up-to-date
