### ISSUE TITLE
解析选择Apk失败

### ISSUE THREAD

**Issue by programmelearn** [Xigong93/XiaoZhuan#9]
java.io.EOFException
	at android.content.res.IntReader.readInt(IntReader.java:104)
	at android.content.res.IntReader.readShort(IntReader.java:69)
	at android.content.res.chunk.sections.StringSection.readPool(StringSection.java:108)
	at android.content.res.chunk.sections.StringSection.readSection(StringSection.java:71)
	at android.content.res.chunk.sections.GenericChunkSection.<init>(GenericChunkSection.java:37)
	at android.content.res.chunk.sections.StringSection.<init>(StringSection.java:48)
	at android.content.res.chunk.ChunkUtil.createChunk(ChunkUtil.java:52)
	at android.content.res.AXMLResource.read(AXMLResource.java:92)
	at android.content.res.AXMLResource.<init>(AXMLResource.java:55)
	at com.dxmwl.newbee.android.ApkParser.getManifestXml(ApkParser.java:49)
	at com.dxmwl.newbee.android.ApkParser.parse(ApkParser.java:21)
	at com.dxmwl.newbee.util.ApkInfoKt$getApkInfo$2.invokeSuspend(ApkInfo.kt:34)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
java.io.IOException: ����Apk�ļ�ʧ��,C:\Users\Administrator\Downloads\goodsDriver_android_20240507112807-8\outputs\v2.8.64_jiagu_signed.apk
	at com.dxmwl.newbee.util.ApkInfoKt$getApkInfo$2.invokeSuspend(ApkInfo.kt:36)
	at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:42)
	at com.dxmwl.newbee.util.ApkInfoKt.getApkInfo(ApkInfo.kt:31)
	at com.dxmwl.newbee.page.home.ApkPageState.parseApkFile(ApkPageState.kt:68)
	at com.dxmwl.newbee.page.home.ApkPageState$selectApkFile$1.invokeSuspend(ApkPageState.kt:251)
Caused by: java.io.IOException: ����Apk�ļ�ʧ��,C:\Users\Administrator\Downloads\goodsDriver_android_20240507112807-8\outputs\v2.8.64_jiagu_signed.apk
	at com.dxmwl.newbee.util.ApkInfoKt$getApkInfo$2.invokeSuspend(ApkInfo.kt:36)
Caused by: java.io.IOException: ����Apk�ļ�ʧ��,C:\Users\Administrator\Downloads\goodsDriver_android_20240507112807-8\outputs\v2.8.64_jiagu_signed.apk

	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
Caused by: java.lang.RuntimeException: ERRORC:\Users\Administrator\Downloads\goodsDriver_android_20240507112807-8\outputs\v2.8.64_jiagu_signed.apk
Caused by: java.lang.RuntimeException: ERRORC:\Users\Administrator\Downloads\goodsDriver_android_20240507112807-8\outputs\v2.8.64_jiagu_signed.apk

	at com.dxmwl.newbee.android.ApkParser.getManifestXml(ApkParser.java:54)
	at com.dxmwl.newbee.android.ApkParser.parse(ApkParser.java:21)
	at com.dxmwl.newbee.util.ApkInfoKt$getApkInfo$2.invokeSuspend(ApkInfo.kt:34)
	... 8 more
Caused by: java.io.IOException
	at android.content.res.AXMLResource.<init>(AXMLResource.java:56)
Caused by: java.io.IOException

	at com.dxmwl.newbee.android.ApkParser.getManifestXml(ApkParser.java:49)
	... 10 more
2024-09-02 10:46:40.158 [AWT-EventQueue-0 @coroutine#4914] Error/应用界面: 解析选择Apk失败 java.io.IOException: 解析Apk文件失败,C:\Users\Administrator\Downloads\goodsDriver_android_20240507112807-8\outputs\v2.8.64_jiagu_signed.apk
	at com.dxmwl.newbee.util.ApkInfoKt$getApkInfo$2.invokeSuspend(ApkInfo.kt:36)
	at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:42)
	at com.dxmwl.newbee.util.ApkInfoKt.getApkInfo(ApkInfo.kt:31)
	at com.dxmwl.newbee.page.home.ApkPageState.parseApkFile(ApkPageState.kt:68)
	at com.dxmwl.newbee.page.home.ApkPageState$selectApkFile$1.invokeSuspend(ApkPageState.kt:251)
Caused by: java.io.IOException: 解析Apk文件失败,C:\Users\Administrator\Downloads\goodsDriver_android_20240507112807-8\outputs\v2.8.64_jiagu_signed.apk
	at com.dxmwl.newbee.util.ApkInfoKt$getApkInfo$2.invokeSuspend(ApkInfo.kt:36)
Caused by: java.io.IOException: 解析Apk文件失败,C:\Users\Administrator\Downloads\goodsDriver_android_20240507112807-8\outputs\v2.8.64_jiagu_signed.apk

	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
Caused by: java.lang.RuntimeException: ERRORC:\Users\Administrator\Downloads\goodsDriver_android_20240507112807-8\outputs\v2.8.64_jiagu_signed.apk
	at com.dxmwl.newbee.android.ApkParser.getManifestXml(ApkParser.java:54)
	at com.dxmwl.newbee.android.ApkParser.parse(ApkParser.java:21)
Caused by: java.lang.RuntimeException: ERRORC:\Users\Administrator\Downloads\goodsDriver_android_20240507112807-8\outputs\v2.8.64_jiagu_signed.apk

	at com.dxmwl.newbee.util.ApkInfoKt$getApkInfo$2.invokeSuspend(ApkInfo.kt:34)
	... 8 more
Caused by: java.io.IOException
	at android.content.res.AXMLResource.<init>(AXMLResource.java:56)
	at com.dxmwl.newbee.android.ApkParser.getManifestXml(ApkParser.java:49)
Caused by: java.io.IOException

	... 10 more

**Comment by Xigong93** [comment]
你好，这个问题是解析apk中的AndroidManifest.xml 中的版本号报错了，解析版本号代码是从安卓系统中拷贝的。
请提供可以复现的方式。

另外请注意提问方式，遇到是什么场景，出现了什么问题，以及如何复现,不要直接贴一堆报错码。

**Comment by programmelearn** [comment]
好的，后面提问注意，我这边是上传包时候报错，目前断点看是这个解析类出问题了AXMLResource，安装包是加固包，还有一个应用能解析出来，是不是包大小超100M导致

**Comment by Xigong93** [comment]
应该不是包大小的问题。

解析版本号的大致流程:
1. 通过zipFile 读取apk文件中的`AndoridManifset.xml`这个Entiry, 得到文件流
2. 读取文件流，通过AXML解析器，得到`AndroidManifst.xml` 文字串内容
3. xml 转Json，有这一步是因为xml解析比较麻烦
4. 从json中读取版本号和版本名称

日志上看出错的是第2步。

```
java.io.EOFException
at android.content.res.IntReader.readInt(IntReader.java:104)
at android.content.res.IntReader.readShort(IntReader.java:69)
at android.content.res.chunk.sections.StringSection.readPool(StringSection.java:108)
at android.content.res.chunk.sections.StringSection.readSection(StringSection.java:71)
at android.content.res.chunk.sections.GenericChunkSection.(GenericChunkSection.java:37)
at android.content.res.chunk.sections.StringSection.(StringSection.java:48)
at android.content.res.chunk.ChunkUtil.createChunk(ChunkUtil.java:52)
at android.content.res.AXMLResource.read(AXMLResource.java:92)  // AXML解析
at android.content.res.AXMLResource.(AXMLResource.java:55)
```

可能的原因：
Apk  加固后生成`AndroidManifxt.xml` ,没法通过项目中的AXML解析器进行解析，具体的原因需要提供这个axml ，运行代码进行测试。

**Comment by programmelearn** [comment]
我提供安装包是否可以

**Comment by Xigong93** [comment]
可以的

**Comment by programmelearn** [comment]
https://pre-imgt.log56.com/cicd/goodsDriver_android/20240730/21/hyb_driver_pro_v2.8.68_jiagu_signed_1020_qrcode.apk

**Comment by Xigong93** [comment]
收到，谢谢，我查一下原因。

**Comment by Xigong93** [comment]
我发现这个安装包的`AndroidManifest.xml` 使用Android Studio 解析Apk，得到的原始xml,有一行报错。
可以修复一下这个问题再试一下，怀疑可能是这个格式错误引起的。
![image](https://github.com/user-attachments/assets/163b2860-cabf-4c53-a9c4-d39a2af7c867)

**Comment by programmelearn** [comment]
好的，我这边也找了一个jar，可以解析包
implementation("net.dongliu:apk-parser:2.6.10")

**Comment by programmelearn** [comment]
代码是正常的     <data android:scheme="tencent1106634391" />   大佬能否删除一下你截图哪个回复呀，公司不让git暴露包信息，虽然都可以解包

**Comment by Xigong93** [comment]
好的，已删除

**Comment by programmelearn** [comment]
感谢大佬，我用了这包implementation("net.dongliu:apk-parser:2.6.10")，已解决问题
![image](https://github.com/user-attachments/assets/47eb1e76-6e14-4c85-9d7b-ac0dfb168ea0)

**Comment by Xigong93** [comment]
好的，不客气
